# agent.R -- constructor for the commons CampusLens agent.
# DuckDB-only backend in v1: loads the synthetic student-retention CSVs
# generated by generate_synthetic_data.R. Uppercase table names match the
# dictionary and measures.

library(commons)
library(ellmer)

Sys.setenv(AWS_REGION = "us-east-1")

make_connection <- function() {
  con <- DBI::dbConnect(duckdb::duckdb())
  DBI::dbWriteTable(con, "STUSL", read.csv("stusl.csv"))
  DBI::dbWriteTable(con, "ACAE", read.csv("acae.csv"))
  DBI::dbWriteTable(con, "TERMGPA", read.csv("termgpa.csv"))
  DBI::dbWriteTable(con, "RETTTE", read.csv("rettte.csv"))
  con
}

# DuckDB needs shutdown = TRUE to fully release its file lock. Safe to call
# from session$onSessionEnded(), where errors are otherwise swallowed.
close_connection <- function(con) {
  DBI::dbDisconnect(con, shutdown = TRUE)
}

make_agent <- function(con = make_connection()) {
  campus <- data_source(
    con,
    tables     = c("STUSL", "ACAE", "TERMGPA", "RETTTE"),
    dictionary = "dictionaries/student.data-dict.yaml"
  )

  commons(
    client         = chat_aws_bedrock(model = "us.anthropic.claude-sonnet-5"),
    data_sources   = list(campus = campus),
    semantic_layer = semantic_layer("measures/retention.R"),
    context_layer  = context_layer(files = c(
      "context/catalog-excerpt.md",
      "context/policy-conventions.md"
    )),
    instructions   = "instructions.md",
    log = TRUE
  )
}
